#!/bin/bash

echo "Instructions for uploading model files to Render:"
echo "================================================"
echo ""
echo "1. First, ensure you have the following model files locally:"
echo "   - yolov3.cfg"
echo "   - yolov3_last.weights (236MB)"
echo "   - yolo.names"
echo "   - d2v_v4.model"
echo ""
echo "2. Connect to your Render service via SSH:"
echo "   ssh srv-d1le8fidbo4c739sl7fg@ssh.singapore.render.com"
echo ""
echo "3. Create the necessary directories:"
echo "   mkdir -p app/static/yolo"
echo "   mkdir -p app/static/data"
echo ""
echo "4. From your local machine, upload the files using SCP:"
echo "   scp yolov3.cfg srv-d1le8fidbo4c739sl7fg@ssh.singapore.render.com:~/app/static/yolo/"
echo "   scp yolov3_last.weights srv-d1le8fidbo4c739sl7fg@ssh.singapore.render.com:~/app/static/yolo/"
echo "   scp yolo.names srv-d1le8fidbo4c739sl7fg@ssh.singapore.render.com:~/app/static/yolo/"
echo "   scp d2v_v4.model srv-d1le8fidbo4c739sl7fg@ssh.singapore.render.com:~/app/static/data/"
echo ""
echo "Alternative: Use cloud storage (recommended for large files)"
echo "============================================================"
echo "1. Upload model files to Google Drive or similar"
echo "2. Update build.sh to download them during deployment"